

import { ToastContainer } from 'react-toastify';
import Sidebar from '../components/sidebar-admin/sidebar';

export const metadata = {
    title: "Diary Journal",
    description: "Generated by create next app",
};



export default function RootLayout({ children }) {
    return (

        <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 flex flex-col min-h-screen">
                <main className="flex-1  bg-gray-50">{children}</main>
            </div>
        </div>
    );
}
